spring.application.name=portfolio

# =========================
# MySQL Database
# =========================

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/portfolio_db}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:Bhavesh@12}

# =========================
# JPA
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# JWT
# =========================

jwt.secret=BhaveshPortfolio2026SecretKeyForJwtAuthenticationSpringBoot
jwt.expiration=3600000

# =========================
# Logging
# =========================

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=TRACE